export const BLOG_TOPICS: string[] = [
  // Cluster 1: ATS Score Improvement
  "How to increase ATS score for TCS NQT 2026",
  "Top 10 resume keywords for Infosys placements",
  "How to bypass Wipro ATS screening",
  "Accenture ASE resume optimization guide",
  "Capgemini resume checklist for freshers",
  "HCL Technologies recruitment resume tips",
  "Cognizant GenC ATS score improvement",
  "Amazon SDE-1 resume preparation India",
  "Flipkart placement resume guide 2026",
  "Deloitte USI resume keywords for freshers",
  "Tech Mahindra placement resume strategy",
  "LTIMindtree recruitment resume tips",
  "Oracle India campus placement guide",
  "Microsoft India resume tips for SDE",
  "Google STEP internship resume guide India",
  "IBM India placement resume optimization",
  "Cisco India recruitment resume checklist",
  "Intel India internship resume guide",
  "Samsung Research India resume tips",
  "Adobe India placement resume strategy",
  "Morgan Stanley India tech resume guide",
  "Goldman Sachs India engineering resume tips",
  "JPMC India tech placement resume checklist",
  "American Express India resume guide",
  "Walmart Global Tech India resume tips",
  "Paytm placement resume strategy 2026",
  "PhonePe tech recruitment resume guide",
  "Zomato engineering placement resume tips",
  "Swiggy tech placement resume guide",
  "Ola tech recruitment resume strategy",
  "Uber India tech placement resume tips",
  "MakeMyTrip placement resume guide",
  "Goibibo tech recruitment resume tips",
  "PolicyBazaar tech placement guide",
  "Nykaa engineering resume strategy",
  "Dream11 tech placement resume tips",
  "CRED tech recruitment resume guide",
  "Razorpay tech placement resume tips",
  "Freshworks placement resume strategy",
  "Zoho tech recruitment resume guide",
  "InMobi tech placement resume tips",
  "BrowserStack recruitment resume guide",
  "Chargebee tech placement resume tips",
  "Postman engineering resume strategy",
  "Hasura tech placement resume guide",
  "Mindtickle tech recruitment tips",
  "Gupshup tech placement resume tips",
  "Darwinbox tech recruitment guide",
  "Druva tech placement resume tips",
  "Icertis tech recruitment guide",
  "HighRadius tech placement tips",
  "Zenoti tech recruitment guide",
  "Capillary tech placement tips",
  "Uniphore tech recruitment guide",
  "Amagi tech placement tips",
  "Fractal Analytics resume guide",
  "Mu Sigma placement resume tips",
  "ZS Associates tech recruitment guide",
  "EXL Service placement resume tips",
  "Genpact tech recruitment guide",
  "Publicis Sapient placement tips",
  "Mindtree tech recruitment guide",
  "Happiest Minds placement tips",
  "Persistent Systems resume guide",
  "KPIT tech recruitment tips",
  "Zensar placement resume guide",
  "Mphasis tech recruitment tips",
  "Coforge placement resume guide",
  "Birlasoft tech recruitment tips",
  "Cyient placement resume guide",
  "Sonata Software recruitment tips",
  "Newgen Software placement tips",
  "Ramco Systems resume guide",
  "Intellect Design placement tips",
  "Nucleus Software recruitment tips",
  "Subex placement resume guide",
  "Tata Elxsi tech recruitment tips",
  "Quest Global placement resume guide",
  "Cybage tech recruitment tips",
  "3i Infotech placement guide",
  "Datamatics recruitment tips",
  "CMS IT Services placement guide",
  "Microland tech recruitment tips",
  "ValueLabs placement resume guide",
  "Indium Software recruitment tips",
  "Aspire Systems placement guide",
  "Kore.ai tech recruitment tips",
  "Yellow.ai placement resume guide",
  "Haptik tech recruitment tips",
  "Senseforth tech placement guide",
  "Stanza Living tech recruitment tips",
  "Livspace tech placement guide",
  "HomeLane tech recruitment tips",
  "Wakefit tech placement guide",
  "Bombay Shaving Company tech tips",
  "mCaffeine tech placement guide",
  "Sugar Cosmetics tech tips",
  "Mamaearth tech placement guide",
  "The Good Glamm Group tech tips",
  "Licious tech placement guide",
  "Country Delight tech tips",
  "MilkBasket tech placement guide",
  "Dunzo tech recruitment tips",
  "Zepto tech placement guide",
  "Blinkit tech recruitment tips",
  "BigBasket tech placement guide",
  "Jio tech recruitment tips",
  "Airtel X Labs placement guide",
  "Vi tech recruitment tips",
  "Adani Group tech placement guide",
  "Reliance Industries tech tips",
  "Tata Group tech placement guide",
  "Mahindra Group tech tips",
  "Birla Group tech placement guide",
  "JSW Group tech tips",
  "Vedanta Group tech placement guide",
  "Hero MotoCorp tech tips",
  "Bajaj Auto tech placement guide",
  "TVS Motor tech tips",
  "Royal Enfield tech placement guide",
  "Maruti Suzuki tech tips",
  "Hyundai India tech placement guide",
  "Kia India tech tips",
  "Toyota India tech placement guide",
  "Honda India tech tips",
  "MG Motor India tech placement guide",
  "Skoda India tech tips",
  "Volkswagen India tech placement guide",
  "Renault India tech tips",
  "Nissan India tech placement guide",
  "Ford India tech tips",
  "General Motors India tech guide",
  "Jeep India tech tips",
  "Citroen India tech placement guide",
  "Volvo India tech tips",
  "Mercedes-Benz India tech guide",
  "BMW India tech tips",
  "Audi India tech placement guide",
  "Jaguar Land Rover India tech tips",
  "Lexus India tech placement guide",
  "Porsche India tech tips",
  "Lamborghini India tech guide",
  "Ferrari India tech tips",
  "Rolls-Royce India tech guide",
  "Bentley India tech tips",
  "Aston Martin India tech guide",
  "Maserati India tech tips",
  "Tesla India recruitment tips",
  "Rivian India recruitment tips",
  "Lucid India recruitment tips",
  "Fisker India recruitment tips",
  "Lordstown India recruitment tips",
  "Canoo India recruitment tips",
  "Faraday Future India tech tips",
  "Nikola India recruitment tips",
  "Workhorse India recruitment tips",
  "Hyliion India recruitment tips",
  "XL Fleet India recruitment tips",
  "GreenPower India recruitment tips",
  "Arrival India recruitment tips",
  "Lion Electric India recruitment tips",
  "Proterra India recruitment tips",
  "BYD India recruitment tips",
  "Nio India recruitment tips",
  "Xpeng India recruitment tips",
  "Li Auto India recruitment tips",
  "Geely India recruitment tips",
  "Chery India recruitment tips",
  "Great Wall India recruitment tips",
  "Changan India recruitment tips",
  "Dongfeng India recruitment tips",
  "FAW India recruitment tips",
  "SAIC India recruitment tips",
  "GAC India recruitment tips",
  "BAIC India recruitment tips",
  "Brilliance India recruitment tips",
  "Zotye India recruitment tips",
  "Lifan India recruitment tips",
  "Luxgen India recruitment tips",
  "VinFast India recruitment tips",
  "Togg India recruitment tips",
  "Sono India recruitment tips",
  "Lightyear India recruitment tips",
  "Aptera India recruitment tips",
  "Elaphe India recruitment tips",
  "Rimac India recruitment tips",
  "Pininfarina India recruitment tips",
  "Koenigsegg India recruitment tips",
  "Pagani India recruitment tips",
  "Bugatti India recruitment tips",
  "McLaren India recruitment tips",
  "Lotus India recruitment tips",
  "Caterham India recruitment tips",
  "Morgan India recruitment tips",
  "TVR India recruitment tips",
  "Noble India recruitment tips",
  "Ginetta India recruitment tips",
  "Ariel India recruitment tips",
  "BAC India recruitment tips",
  "Ultima India recruitment tips",
  "Radical India recruitment tips",
  "Bowler India recruitment tips",
  "David Brown India recruitment tips",
  "Eagle India recruitment tips",
  "Lister India recruitment tips",
  "Zenos India recruitment tips",
  "Elemental India recruitment tips",
  "Riversimple India recruitment tips",
  "McMurtry India recruitment tips",
  "Gordon Murray India recruitment tips",
  "Ineos India recruitment tips",
  "Jianhe India recruitment tips",
  "Aiways India recruitment tips",
  "Arcfox India recruitment tips",
  "Enovate India recruitment tips",
  "HiPhi India recruitment tips",
  "Hozon India recruitment tips",
  "Hycan India recruitment tips",
  "IM India recruitment tips",
  "Jidu India recruitment tips",
  "Leapmotor India recruitment tips",
  "Neta India recruitment tips",
  "Ora India recruitment tips",
  "Polestar India recruitment tips",
  "Qiantu India recruitment tips",
  "Seres India recruitment tips",
  "Skyworth India recruitment tips",
  "Voyah India recruitment tips",
  "Weltmeister India recruitment tips",
  "Zeekr India recruitment tips",
  "Zhiji India recruitment tips",
  "Zhidou India recruitment tips",
  "Wuling India recruitment tips",
  "Baojun India recruitment tips",
  "Trumpchi India recruitment tips",
  "Aion India recruitment tips",
  "Hycan India recruitment tips",
  "Jetta India recruitment tips",
  "VGV India recruitment tips",
  "Oshan India recruitment tips",
  "Jetour India recruitment tips",
  "Exeed India recruitment tips",
  "Cowin India recruitment tips",
  "Borgward India recruitment tips",
  "Hanteng India recruitment tips",
  "Traum India recruitment tips",
  "Dorcen India recruitment tips",
  "Junpai India recruitment tips",
  "Senia India recruitment tips",
  "Venuccia India recruitment tips",
  "Qoros India recruitment tips",
  "Landwind India recruitment tips",
  "Jonway India recruitment tips",
  "Hawtai India recruitment tips",
  "Huanghai India recruitment tips",
  "Gonow India recruitment tips",
  "Fuqi India recruitment tips",
  "Dadi India recruitment tips",
  "Changfeng India recruitment tips",
  "Shuanghuan India recruitment tips",
  "Tianma India recruitment tips",
  "Xinkai India recruitment tips",
  "Youngman India recruitment tips",
  "Zhongxing India recruitment tips",
  "Bisu India recruitment tips",
  "Huansu India recruitment tips",
  "Karry India recruitment tips",
  "Rely India recruitment tips",
  "Riich India recruitment tips",
  "Englon India recruitment tips",
  "Gleagle India recruitment tips",
  "Emgrand India recruitment tips",
  "Zotye India recruitment tips",
  "Jiangnan India recruitment tips",
  "Hanlong India recruitment tips",
  "Tebian India recruitment tips",
  "Yudo India recruitment tips",
  "Singulato India recruitment tips",
  "Sitech India recruitment tips",
  "Zedriv India recruitment tips",
  "Dearcc India recruitment tips",
  "Enovate India recruitment tips",
  "Levdeo India recruitment tips",
  "Pocco India recruitment tips",
  "Letin India recruitment tips",
  "Lingbox India recruitment tips",
  "Jiayuan India recruitment tips",
  "Today Sunshine India tips",
  "Lichi India recruitment tips",
  "Yema India recruitment tips",
  "Levdeo India recruitment tips",
  "Pocco India recruitment tips",
  "Letin India recruitment tips",
  "Lingbox India recruitment tips",
  "Jiayuan India recruitment tips",
  "Today Sunshine India tips",
  "Lichi India recruitment tips",
  "Yema India recruitment tips",
  "Levdeo India recruitment tips",
  "Pocco India recruitment tips",
  "Letin India recruitment tips",
  "Lingbox India recruitment tips",
  "Jiayuan India recruitment tips",
  "Today Sunshine India tips",
  "Lichi India recruitment tips",
  "Yema India recruitment tips",
  "How to list internships on Indian resume",
  "CGPA vs Skills: What Indian recruiters want",
  "Best resume format for Tier-3 college students",
  "How to handle gaps in Indian resume",
  "Resume tips for non-CS students in IT",
  "How to mention NPTEL courses on resume",
  "Role of projects in Indian campus placements",
  "How to write a resume for off-campus drives",
  "Common resume mistakes Indian students make",
  "How to tailor resume for product companies",
  "How to tailor resume for service companies",
  "Resume tips for Indian students with no intern",
  "How to list coding profiles on resume",
  "Best certifications for Indian IT freshers",
  "How to write resume for startup jobs India",
  "Resume tips for final year engineering students",
  "How to use LinkedIn for Indian placements",
  "Resume vs CV: Difference for Indian freshers",
  "How many pages should an Indian resume be?",
  "Best fonts for Indian placement resumes",
  "How to write resume for core engineering jobs",
  "Resume tips for MCA students India",
  "Resume tips for BCA students India",
  "Resume tips for BSc IT students India",
  "How to mention hackathons on Indian resume",
  "Resume tips for pre-final year students",
  "How to list research papers on Indian resume",
  "Resume tips for higher studies vs jobs",
  "How to handle low CGPA on Indian resume",
  "Resume tips for lateral entry students",
  "Importance of soft skills in Indian resume",
  "How to write resume for data science freshers",
  "How to write resume for AI/ML roles India",
  "How to write resume for cybersecurity freshers",
  "How to write resume for cloud roles India",
  "Resume tips for mobile app dev freshers",
  "Resume tips for web dev freshers India",
  "How to list open source on Indian resume",
  "Resume tips for competitive programmers",
  "How to write resume for fintech jobs India",
  "Resume tips for edtech jobs India freshers",
  "Resume tips for e-commerce jobs India",
  "How to write resume for healthtech jobs",
  "Resume tips for agritech jobs India",
  "How to write resume for logitech jobs India",
  "Resume tips for spacetech jobs India",
  "How to write resume for clean tech jobs",
  "Resume tips for EV industry jobs India",
  "How to write resume for drone industry India",
  "Resume tips for robotics jobs India",
  "How to write resume for gaming industry India",
  "Resume tips for AR/VR jobs India freshers",
  "How to write resume for blockchain jobs India",
  "Resume tips for web3 jobs India freshers",
  "How to write resume for 5G/Telecom jobs",
  "Resume tips for semiconductor jobs India",
  "How to write resume for embedded systems",
  "Resume tips for VLSI jobs India freshers",
  "How to write resume for power electronics",
  "Resume tips for renewable energy jobs",
  "How to write resume for manufacturing jobs",
  "Resume tips for supply chain jobs India",
  "How to write resume for retail tech jobs",
  "Resume tips for food tech jobs India",
  "How to write resume for travel tech jobs",
  "Resume tips for hospitality tech jobs",
  "How to write resume for prop tech jobs India",
  "Resume tips for legal tech jobs India",
  "How to write resume for hr tech jobs India",
  "Resume tips for ad tech jobs India freshers",
  "How to write resume for deep tech jobs India",
  "Resume tips for hardware engineering jobs",
  "How to write resume for civil engineering jobs",
  "Resume tips for mechanical engineering jobs",
  "How to write resume for electrical engineering",
  "Resume tips for electronics engineering jobs",
  "How to write resume for chemical engineering",
  "Resume tips for biotech engineering jobs",
  "How to write resume for food technology jobs",
  "Resume tips for petroleum engineering jobs",
  "How to write resume for mining engineering",
  "Resume tips for textile engineering jobs",
  "How to write resume for production engineering",
  "Resume tips for instrumentation engineering",
  "How to write resume for aerospace engineering",
  "Resume tips for marine engineering jobs",
  "How to write resume for automobile engineering",
  "Resume tips for environmental engineering",
  "How to write resume for agriculture engineering",
  "Resume tips for printing technology jobs",
  "How to write resume for fashion technology",
  "Resume tips for architecture students India",
  "How to write resume for interior design jobs",
  "Resume tips for graphic design jobs India",
  "How to write resume for animation jobs India",
  "Resume tips for vfx jobs India freshers",
  "How to write resume for UI/UX jobs India",
  "Resume tips for digital marketing jobs India",
  "How to write resume for content writing jobs",
  "Resume tips for social media manager jobs",
  "How to write resume for SEO jobs India",
  "Resume tips for SEM/PPC jobs India freshers",
  "How to write resume for affiliate marketing",
  "Resume tips for influencer marketing jobs",
  "How to write resume for public relations",
  "Resume tips for event management jobs India",
  "How to write resume for advertising jobs",
  "Resume tips for journalism jobs India",
  "How to write resume for mass communication",
  "Resume tips for film/tv production jobs",
  "How to write resume for radio jockey jobs",
  "Resume tips for photographer jobs India",
  "How to write resume for videographer jobs",
  "Resume tips for editor jobs India freshers",
  "How to write resume for sound engineer jobs",
  "Resume tips for music production jobs India",
  "How to write resume for performing arts jobs",
  "Resume tips for sports management jobs India",
  "How to write resume for physical education",
  "Resume tips for yoga instructor jobs India",
  "How to write resume for nutritionist jobs",
  "Resume tips for psychologist jobs India",
  "How to write resume for counselor jobs India",
  "Resume tips for teacher jobs India freshers",
  "How to write resume for professor jobs India",
  "Resume tips for research scholar jobs India",
  "How to write resume for scientist jobs India",
  "Resume tips for doctor jobs India freshers",
  "How to write resume for nurse jobs India",
  "Resume tips for pharmacist jobs India",
  "How to write resume for physiotherapist jobs",
  "Resume tips for dentist jobs India freshers",
  "How to write resume for vet jobs India",
  "Resume tips for lawyer jobs India freshers",
  "How to write resume for chartered accountant",
  "Resume tips for company secretary jobs India",
  "How to write resume for cost accountant jobs",
  "Resume tips for actuary jobs India freshers",
  "How to write resume for stock broker jobs",
  "Resume tips for investment banker jobs India",
  "How to write resume for insurance agent jobs",
  "Resume tips for real estate agent jobs India",
  "How to write resume for travel agent jobs",
  "Resume tips for chef jobs India freshers",
  "How to write resume for hotel manager jobs",
  "Resume tips for pilot jobs India freshers",
  "How to write resume for cabin crew jobs",
  "Resume tips for air traffic controller jobs",
  "How to write resume for merchant navy jobs",
  "Resume tips for army/navy/airforce jobs",
  "How to write resume for police/ias/ips jobs",
  "Resume tips for government jobs India",
  "How to write resume for ngo jobs India",
  "Resume tips for social worker jobs India",
  "How to write resume for volunteer jobs India",
  "Resume tips for internship in India",
  "How to write resume for remote jobs India",
  "Resume tips for freelance jobs India",
  "How to write resume for part-time jobs India",
  "Resume tips for work from home jobs India"
];
