"use client";

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ArrowLeft, Sparkles, FileText, Download, Target, 
  Briefcase, Brain, CheckCircle2, ChevronRight, Loader2,
  Trash2, Copy, Check
} from 'lucide-react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { useSession } from "next-auth/react";
import Link from 'next/link';
import { ExpertGate } from "@/components/ExpertGate";

export default function ExpertResumeBuilder() {
  const { data: session, status } = useSession();
  const [originalText, setOriginalText] = useState("");
  const [targetRole, setTargetRole] = useState("");
  const [experienceLevel, setExperienceLevel] = useState("Fresher / Entry Level");
  const [keySkills, setKeySkills] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [isCopied, setIsCopied] = useState(false);

  const isExpert = session?.user?.email === "admin@placementscore.online";

  const handleGenerate = async () => {
    if (!session) return alert("Please sign in.");
    if (!originalText || !targetRole) return alert("Please fill all fields.");

    setIsGenerating(true);
    setResult(null);

    try {
      const response = await fetch('/api/ai-build-resume', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: session.user?.email,
          plan: "expert",
          originalResumeText: originalText,
          targetRole,
          experienceLevel,
          keySkills
        })
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      setResult(data);
    } catch (err: any) {
      alert(err.message || "Something went wrong");
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPDF = async () => {
    if (!result) return;
    try {
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([600, 800]);
      const { height } = page.getSize();
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      page.drawText('ATS OPTIMIZED RESUME', { x: 50, y: height - 50, size: 18, font: boldFont, color: rgb(0.1, 0.4, 0.8) });
      page.drawText(`Generated by PlacementScore AI for ${targetRole}`, { x: 50, y: height - 70, size: 10, font, color: rgb(0.5, 0.5, 0.5) });

      const text = result.optimizedResumeText;
      const lines = text.split('\n');
      let yOffset = height - 110;

      for (const line of lines) {
        if (yOffset < 50) {
          const newPage = pdfDoc.addPage([600, 800]);
          yOffset = 750;
        }
        page.drawText(line.substring(0, 95), { x: 50, y: yOffset, size: 10, font, color: rgb(0.2, 0.2, 0.2) });
        yOffset -= 15;
      }

      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes as any], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Optimized_${targetRole.replace(/\s/g, '_')}_Resume.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) { alert("Failed to generate PDF."); }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result.optimizedResumeText);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  if (status === "loading") return <div className="min-h-screen bg-black flex items-center justify-center font-black italic animate-pulse">Checking credentials...</div>;

  return (
    <div className="min-h-screen bg-[#050505] text-white p-6 pt-32 relative overflow-hidden">
      <div className="absolute top-[-5%] left-[-10%] w-[50%] h-[50%] bg-blue-600/[0.03] blur-[120px] rounded-full pointer-events-none" />
      
      <div className="max-w-5xl mx-auto relative z-10">
        <Link href="/" className="inline-flex items-center gap-2 text-white/20 hover:text-white mb-8 transition-colors group">
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> Back to Home
        </Link>

        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-16">
          <div className="space-y-2">
            <h1 className="text-5xl md:text-7xl font-[1000] italic uppercase tracking-tighter flex items-center gap-4 italic">
              AI Resume Builder <Sparkles className="text-blue-500 w-10 h-10" />
            </h1>
            <p className="text-white/30 font-bold uppercase tracking-widest text-xs">Architecting your high-performance career profile</p>
          </div>
          {result && (
            <button onClick={downloadPDF} className="bg-blue-600 text-white px-10 py-5 rounded-2xl font-black flex items-center gap-4 hover:bg-blue-500 transition-all shadow-2xl shadow-blue-500/30 uppercase italic">
              <Download className="w-6 h-6" /> Download PDF
            </button>
          )}
        </div>

        <ExpertGate isExpert={isExpert}>
          <div className="grid lg:grid-cols-1 gap-12 text-left">
            {!result ? (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-[#0A0A0A] p-10 md:p-16 rounded-[60px] border border-white/5 space-y-12 shadow-2xl">
                <div className="space-y-10">
                  <div className="space-y-4">
                    <label className="text-[10px] font-[1000] uppercase text-white/20 ml-2 tracking-[0.4em]">1. Current Resume / Profile Draft</label>
                    <textarea 
                      value={originalText}
                      onChange={(e) => setOriginalText(e.target.value)}
                      placeholder="Paste your resume content here..."
                      className="w-full h-80 p-8 bg-black border border-white/10 rounded-[40px] outline-none focus:border-blue-600 transition-all font-medium text-white/80 resize-none shadow-inner no-scrollbar"
                    />
                  </div>

                  <div className="grid md:grid-cols-2 gap-12">
                    <div className="space-y-4">
                      <label className="text-[10px] font-[1000] uppercase text-white/20 ml-2 tracking-[0.4em]">2. Target Job Role</label>
                      <div className="relative">
                        <Target className="absolute left-8 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-500" />
                        <input 
                          type="text" 
                          value={targetRole}
                          onChange={(e) => setTargetRole(e.target.value)}
                          placeholder="e.g. SDE-1 @ Google"
                          className="w-full p-6 pl-20 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-black text-xl italic"
                        />
                      </div>
                    </div>
                    <div className="space-y-4">
                      <label className="text-[10px] font-[1000] uppercase text-white/20 ml-2 tracking-[0.4em]">3. Experience Tier</label>
                      <div className="relative">
                        <Briefcase className="absolute left-8 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-500" />
                        <select 
                          value={experienceLevel}
                          onChange={(e) => setExperienceLevel(e.target.value)}
                          className="w-full p-6 pl-20 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-black text-xl italic appearance-none cursor-pointer"
                        >
                          <option>Fresher / Entry Level</option>
                          <option>Junior (1-3 Years)</option>
                          <option>Mid-Level (3-7 Years)</option>
                          <option>Senior (7+ Years)</option>
                        </select>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <label className="text-[10px] font-[1000] uppercase text-white/20 ml-2 tracking-[0.4em]">4. Skills to Prioritize</label>
                    <div className="relative">
                      <Brain className="absolute left-8 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-500" />
                      <input 
                        type="text" 
                        value={keySkills}
                        onChange={(e) => setKeySkills(e.target.value)}
                        placeholder="e.g. Next.js, AWS, System Design"
                        className="w-full p-6 pl-20 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-black text-xl italic"
                      />
                    </div>
                  </div>
                </div>

                <button 
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  className="w-full py-10 bg-blue-600 rounded-[40px] font-[1000] text-3xl text-white hover:bg-blue-500 transition-all shadow-2xl shadow-blue-500/30 uppercase italic tracking-tighter flex items-center justify-center gap-6 disabled:opacity-50"
                >
                  {isGenerating ? <Loader2 className="w-10 h-10 animate-spin" /> : <>Build My Optimized Resume <Sparkles className="w-8 h-8" /></>}
                </button>
              </motion.div>
            ) : (
              <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="space-y-12">
                <div className="grid lg:grid-cols-3 gap-12">
                  <div className="lg:col-span-2 bg-[#0A0A0A] border border-white/5 rounded-[60px] p-10 md:p-16 shadow-2xl relative overflow-hidden text-left">
                    <div className="flex justify-between items-center mb-12 text-left">
                      <h3 className="text-2xl font-[1000] uppercase italic tracking-tighter text-blue-500 flex items-center gap-3">
                        <FileText className="w-6 h-6" /> AI-Generated Blueprint
                      </h3>
                      <div className="flex gap-4 text-left">
                        <button onClick={copyToClipboard} className="p-4 bg-white/5 border border-white/5 rounded-2xl hover:bg-white/10 transition-all">
                          {isCopied ? <Check className="w-6 h-6 text-green-500" /> : <Copy className="w-6 h-6 text-white/40" />}
                        </button>
                        <button onClick={() => setResult(null)} className="p-4 bg-white/5 border border-white/5 rounded-2xl hover:bg-red-600/20 transition-all">
                          <Trash2 className="w-6 h-6 text-white/40" />
                        </button>
                      </div>
                    </div>
                    <div className="bg-black/50 p-10 rounded-[40px] border border-white/5 font-mono text-base leading-loose text-white/60 h-[700px] overflow-y-auto no-scrollbar whitespace-pre-wrap">
                      {result.optimizedResumeText}
                    </div>
                  </div>

                  <div className="space-y-10 text-left">
                    <div className="bg-blue-600/10 border border-blue-600/20 rounded-[50px] p-10 space-y-8 shadow-2xl">
                      <div className="text-center space-y-2">
                        <h4 className="text-[10px] font-black uppercase tracking-[0.5em] text-blue-400 italic">ATS Confidence Level</h4>
                        <div className="text-8xl font-[1000] italic text-white leading-none">{result.atsScoreEstimate}</div>
                        <p className="text-[10px] font-bold text-white/20 uppercase tracking-widest pt-2">Highly Optimized for MNCs</p>
                      </div>
                      <div className="h-3 w-full bg-white/5 rounded-full overflow-hidden">
                        <motion.div initial={{ width: 0 }} animate={{ width: `${result.atsScoreEstimate}%` }} className="h-full bg-blue-500 shadow-[0_0_30px_rgba(59,130,246,0.6)]" />
                      </div>
                    </div>

                    <div className="bg-white/5 border border-white/5 rounded-[50px] p-10 space-y-8">
                      <h4 className="text-[10px] font-black uppercase tracking-[0.5em] text-white/20 flex items-center gap-3 italic text-left">
                        <CheckCircle2 className="w-5 h-5 text-green-500" /> Neural Optimizations
                      </h4>
                      <ul className="space-y-6 text-left">
                        {result.suggestedImprovements.map((imp: string, i: number) => (
                          <li key={i} className="text-base font-bold text-white/40 flex items-start gap-4 italic leading-snug">
                            <ChevronRight className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
                            {imp}
                          </li>
                        ))}
                      </ul>
                    </div>

                    <button onClick={downloadPDF} className="w-full py-8 bg-white text-black rounded-[30px] font-[1000] text-2xl hover:bg-blue-600 hover:text-white transition-all shadow-2xl flex items-center justify-center gap-4 uppercase italic tracking-tighter">
                      <Download className="w-6 h-6" /> Export PDF Resume
                    </button>
                  </div>
                </div>
              </motion.div>
            )}
          </div>
        </ExpertGate>
      </div>
    </div>
  );
}
