"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ArrowLeft, Sparkles, FileText, Download, Target, 
  Briefcase, Brain, CheckCircle2, ChevronRight, Loader2,
  Trash2, Copy, Check
} from 'lucide-react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export default function ExpertResumeBuilder() {
  const [originalText, setOriginalText] = useState("");
  const [targetRole, setTargetRole] = useState("");
  const [experienceLevel, setExperienceLevel] = useState("Entry Level");
  const [keySkills, setKeySkills] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [isCopied, setIsCopied] = useState(false);

  // Mock User Check (In real app, this comes from Auth Context/Session)
  const userPlan = "expert"; 

  const handleGenerate = async () => {
    if (!originalText || !targetRole) {
      alert("Please enter your resume text and target role.");
      return;
    }

    setIsGenerating(true);
    setResult(null);

    try {
      const response = await fetch('/api/ai-build-resume', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: "urboss",
          plan: "expert",
          originalResumeText: originalText,
          targetRole,
          experienceLevel,
          keySkills
        })
      });

      const data = await response.json();

      if (!response.ok) throw new Error(data.error);

      setResult(data);
    } catch (err: any) {
      alert(err.message || "Something went wrong");
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPDF = async () => {
    if (!result) return;

    try {
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([600, 800]);
      const { width, height } = page.getSize();
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      page.drawText('ATS OPTIMIZED RESUME', {
        x: 50,
        y: height - 50,
        size: 18,
        font: boldFont,
        color: rgb(0.1, 0.4, 0.8),
      });

      page.drawText(`Generated by PlacementScore AI for ${targetRole}`, {
        x: 50,
        y: height - 70,
        size: 10,
        font: font,
        color: rgb(0.5, 0.5, 0.5),
      });

      const text = result.optimizedResumeText;
      const lines = text.split('\n');
      let yOffset = height - 110;

      for (const line of lines) {
        if (yOffset < 50) {
          // Add new page if space is low
          const newPage = pdfDoc.addPage([600, 800]);
          yOffset = 750;
        }
        
        // Basic line wrapping for simple text
        const fontSize = 10;
        page.drawText(line.substring(0, 95), {
          x: 50,
          y: yOffset,
          size: fontSize,
          font: line.toUpperCase() === line && line.length > 3 ? boldFont : font,
          color: rgb(0.2, 0.2, 0.2),
        });
        yOffset -= 15;
      }

      const pdfBytes = await pdfDoc.save();
      // Use the underlying buffer directly to avoid Uint8Array/ArrayBufferLike TS conflicts
      const blob = new Blob([pdfBytes.buffer], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Optimized_${targetRole.replace(/\s/g, '_')}_Resume.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      console.error("PDF Export Error:", err);
      alert("Failed to generate PDF. You can still copy the text below.");
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result.optimizedResumeText);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#050505] text-white p-6 pt-32">
      <div className="max-w-4xl mx-auto">
        <button onClick={() => window.history.back()} className="flex items-center gap-2 text-white/40 hover:text-white mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </button>

        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-12">
          <div className="space-y-2">
            <h1 className="text-4xl font-[1000] italic uppercase tracking-tighter flex items-center gap-4">
              AI Resume Builder <Sparkles className="text-blue-500 w-8 h-8" />
            </h1>
            <p className="text-white/30 font-bold uppercase tracking-widest text-xs">Expert Plan Exclusive Feature</p>
          </div>
          {result && (
            <button onClick={downloadPDF} className="bg-blue-600 text-white px-8 py-4 rounded-2xl font-black flex items-center gap-3 hover:bg-blue-500 transition-all shadow-xl shadow-blue-600/20">
              <Download className="w-5 h-5" /> Download PDF
            </button>
          )}
        </div>

        <div className="grid lg:grid-cols-1 gap-12">
          {!result ? (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-[#0A0A0A] p-8 md:p-12 rounded-[40px] border border-white/5 space-y-10 shadow-2xl">
              <div className="space-y-6">
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase text-white/20 ml-2 tracking-[0.3em]">Paste Existing Resume or Draft</label>
                  <textarea 
                    value={originalText}
                    onChange={(e) => setOriginalText(e.target.value)}
                    placeholder="Paste your current resume content here..."
                    className="w-full h-64 p-6 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-medium text-white/80 resize-none"
                  />
                </div>

                <div className="grid md:grid-cols-2 gap-8">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase text-white/20 ml-2 tracking-[0.3em]">Target Job Role</label>
                    <div className="relative">
                      <Target className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-white/20" />
                      <input 
                        type="text" 
                        value={targetRole}
                        onChange={(e) => setTargetRole(e.target.value)}
                        placeholder="e.g. Senior Frontend Engineer"
                        className="w-full p-6 pl-16 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-bold"
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase text-white/20 ml-2 tracking-[0.3em]">Experience Level</label>
                    <div className="relative">
                      <Briefcase className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-white/20" />
                      <select 
                        value={experienceLevel}
                        onChange={(e) => setExperienceLevel(e.target.value)}
                        className="w-full p-6 pl-16 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-bold appearance-none cursor-pointer"
                      >
                        <option>Fresher / Entry Level</option>
                        <option>Junior (1-3 Years)</option>
                        <option>Mid-Level (3-7 Years)</option>
                        <option>Senior (7+ Years)</option>
                        <option>Leadership / Manager</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase text-white/20 ml-2 tracking-[0.3em]">Specific Skills to Emphasize</label>
                  <div className="relative">
                    <Brain className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-white/20" />
                    <input 
                      type="text" 
                      value={keySkills}
                      onChange={(e) => setKeySkills(e.target.value)}
                      placeholder="e.g. Next.js, AWS, Kubernetes, System Design"
                      className="w-full p-6 pl-16 bg-black border border-white/10 rounded-3xl outline-none focus:border-blue-600 transition-all font-bold"
                    />
                  </div>
                </div>
              </div>

              <button 
                onClick={handleGenerate}
                disabled={isGenerating}
                className="w-full py-8 bg-blue-600 rounded-[32px] font-[1000] text-2xl hover:bg-blue-500 transition-all shadow-2xl shadow-blue-600/20 uppercase italic tracking-tighter flex items-center justify-center gap-4 disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-8 h-8 animate-spin" />
                    Rearchitecting...
                  </>
                ) : (
                  <>
                    Generate ATS Optimized Resume
                    <Sparkles className="w-6 h-6" />
                  </>
                )}
              </button>
            </motion.div>
          ) : (
            <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="space-y-8">
              <div className="grid md:grid-cols-3 gap-6">
                <div className="md:col-span-2 bg-[#0A0A0A] border border-white/10 rounded-[40px] p-8 md:p-12 shadow-2xl relative">
                  <div className="flex justify-between items-center mb-8">
                    <h3 className="text-xl font-black uppercase italic tracking-widest text-blue-500 flex items-center gap-2">
                      <FileText className="w-5 h-5" /> Optimized Resume Preview
                    </h3>
                    <div className="flex gap-2">
                      <button onClick={copyToClipboard} className="p-3 bg-white/5 border border-white/5 rounded-xl hover:bg-white/10 transition-all text-white/40 hover:text-white">
                        {isCopied ? <Check className="w-5 h-5 text-green-500" /> : <Copy className="w-5 h-5" />}
                      </button>
                      <button onClick={() => setResult(null)} className="p-3 bg-white/5 border border-white/5 rounded-xl hover:bg-red-500/20 transition-all text-white/40 hover:text-red-500">
                        <Trash2 className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                  <div className="bg-black/50 p-8 rounded-3xl border border-white/5 font-mono text-sm leading-relaxed text-white/70 h-[600px] overflow-y-auto no-scrollbar whitespace-pre-wrap">
                    {result.optimizedResumeText}
                  </div>
                </div>

                <div className="space-y-6">
                  <div className="bg-blue-600/10 border border-blue-600/20 rounded-[40px] p-8 space-y-6">
                    <div className="text-center space-y-2">
                      <h4 className="text-[10px] font-black uppercase tracking-widest text-blue-400">Estimated ATS Score</h4>
                      <div className="text-6xl font-[1000] italic text-white">{result.atsScoreEstimate}</div>
                    </div>
                    <div className="h-2 w-full bg-white/5 rounded-full overflow-hidden">
                      <motion.div initial={{ width: 0 }} animate={{ width: `${result.atsScoreEstimate}%` }} className="h-full bg-blue-500 shadow-[0_0_20px_rgba(59,130,246,0.5)]" />
                    </div>
                  </div>

                  <div className="bg-white/5 border border-white/10 rounded-[40px] p-8">
                    <h4 className="text-[10px] font-black uppercase tracking-widest text-white/30 mb-6 flex items-center gap-2 italic">
                      <CheckCircle2 className="w-4 h-4 text-green-500" /> AI Improvements Made
                    </h4>
                    <ul className="space-y-4">
                      {result.suggestedImprovements.map((imp: string, i: number) => (
                        <li key={i} className="text-sm font-bold text-white/60 flex items-start gap-3">
                          <ChevronRight className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
                          {imp}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <button onClick={downloadPDF} className="w-full py-6 bg-white text-black rounded-3xl font-black text-xl hover:bg-blue-600 hover:text-white transition-all shadow-2xl flex items-center justify-center gap-3">
                    <Download className="w-5 h-5" /> Download PDF
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </div>
      </div>
    </div>
  );
}
