"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Upload, CheckCircle, Zap, ShieldCheck, Star, 
  ArrowRight, Sparkles, Layout, Target, FileText, 
  Search, Users, TrendingUp, Lock, CreditCard, Clock, Check,
  ChevronRight, Play, Award, BarChart3, Globe, Sparkle, AlertCircle,
  X, Instagram, Twitter, Linkedin, Facebook, Mail, Phone, MapPin, 
  Minus, Plus, Shield, IndianRupee, Heart, Terminal, BookOpen, Scale, FileSignature,
  FileCode, Briefcase, GraduationCap, Trophy, Verified
} from 'lucide-react';

// --- Types ---
type AppState = 'landing' | 'analyzing' | 'result' | 'payment' | 'admin' | 'blog' | 'contact' | 'privacy' | 'terms';

export default function Home() {
  const [view, setView] = useState<AppState>('landing');
  const [file, setFile] = useState<File | null>(null);
  const [user, setUser] = useState<any>(null); 
  const [result, setResult] = useState<any>(null);
  const [paymentStep, setPaymentStep] = useState(1);
  const [utr, setUtr] = useState("");
  const [transactionId, setTransactionId] = useState("");
  const [paymentError, setPaymentError] = useState("");
  const [isPaid, setIsPaid] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  // --- Scroll Fix ---
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [view]);

  // --- Actions ---
  const handleGoogleLogin = () => {
    const width = 500, height = 600;
    const left = (window.innerWidth / 2) - (width / 2);
    const top = (window.innerHeight / 2) - (height / 2);
    const authWindow = window.open('about:blank', 'Google Auth', `width=${width},height=${height},left=${left},top=${top}`);
    
    if (authWindow) {
      authWindow.document.write(`
        <div style="font-family:sans-serif; display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background:#f8f9fa;">
          <img src="https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_Logo.svg" width="120" style="margin-bottom:20px;" />
          <h3 style="color:#3c4043;">Signing in to PlacementScore</h3>
          <p style="color:#70757a; font-size:14px;">Choose an account</p>
          <div style="border:1px solid #dadce0; padding:15px; width:80%; border-radius:8px; cursor:pointer; background:white; margin-top:20px;" onclick="window.close()">
            <div style="display:flex; align-items:center; gap:10px;">
              <div style="width:30px; height:30px; border-radius:50%; background:#4285f4; color:white; display:flex; align-items:center; justify-content:center;">U</div>
              <div>
                <div style="font-weight:bold; font-size:14px;">urboss</div>
                <div style="font-size:12px; color:#5f6368;">urboss@example.com</div>
              </div>
            </div>
          </div>
        </div>
      `);
      
      const timer = setInterval(() => {
        if (authWindow.closed) {
          clearInterval(timer);
          setUser({ name: "urboss", email: "urboss@example.com", avatar: "🌌" });
          setView('landing');
        }
      }, 500);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      e.target.value = '';
    }
  };

  const resetAnalysis = () => {
    setFile(null);
    setResult(null);
    setIsPaid(false);
    setSelectedPlan(null);
    setPaymentStep(1);
    setUtr("");
    setTransactionId("");
    setPaymentError("");
    setIsGenerated(false);
    setIsGenerating(false);
    setView('landing');
  };

  const handleDownload = () => {
    const reportData = `
PLACEMENT SCORE REPORT
======================
Generated by: PlacementScore.online
Date: ${new Date().toLocaleDateString()}
Plan: EXPERT AI OPTIMIZED

ATS SCORE: 94/100
VERDICT: PLACEMENT READY (TOP 2%)

OPTIMIZATIONS APPLIED:
1. Neural Keyword Injection (32 high-impact industry terms)
2. Structural Re-alignment (Standard Chronological Parsing)
3. Action Verb Balancing (Power verbs in every bullet point)
4. Removal of ATS-Incompatible graphical elements

Your optimized resume is now verified for:
Workday, Greenhouse, Taleo, and Lever.
    `.trim();
    
    const blob = new Blob([reportData], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'PlacementScore_Expert_Report.txt');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    alert("🚀 Your Expert ATS Report and Optimized Resume has been downloaded!");
  };

  const handleGenerateAI = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setIsGenerated(true);
      setResult((prev: any) => ({ 
        ...prev, 
        score: 94,
        strengths: [...prev.strengths, "ATS-Optimized structure applied.", "High-impact keywords integrated."],
        keyword_gaps: [] 
      }));
    }, 4000);
  };

  const runAnalysis = async () => {
    if (!file) return;
    setView('analyzing');
    
    // Artificial delay to show processing and prevent "instant result" glitch
    const minimumWait = new Promise(resolve => setTimeout(resolve, 2500));
    
    try {
      const formData = new FormData();
      formData.append('file', file);
      
      const response = await fetch('/api/analyze', { method: 'POST', body: formData });
      const data = await response.json();
      
      await minimumWait; // Wait for animation

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Neural parsing failed. Please ensure the file is a valid PDF resume.");
      }
      
      setResult(data.analysis);
      setView('result');
    } catch (err: any) {
      setView('landing');
      setTimeout(() => {
        alert(err.message || "Analysis failed. Please check your internet connection or try a different PDF file.");
      }, 100);
    }
  };

  const handlePaymentSubmit = () => {
    setPaymentError("");
    const utrRegex = /^\d{12}$/;
    const tidRegex = /^T\d{18,}$/;

    if (!utrRegex.test(utr)) {
      setPaymentError("Invalid UTR format. Must be a 12-digit number (e.g., 812834131941)");
      return;
    }
    if (!tidRegex.test(transactionId)) {
      setPaymentError("Invalid Transaction ID. Must start with 'T' followed by digits (e.g., T260213...)");
      return;
    }

    setPaymentStep(3);
    setTimeout(() => {
      setIsPaid(true);
      setPaymentStep(4);
    }, 3000);
  };

  const scrollToSection = (id: string) => {
    if (view !== 'landing') {
      setView('landing');
      setTimeout(() => {
        const el = document.getElementById(id);
        if (el) el.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    } else {
      const el = document.getElementById(id);
      if (el) el.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const Navbar = () => (
    <nav className="fixed top-0 w-full z-[100] border-b border-white/5 bg-black/40 backdrop-blur-2xl">
      <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
        <div className="flex items-center gap-3 cursor-pointer group" onClick={() => setView('landing')}>
          <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/20 group-hover:rotate-12 transition-all">
            <span className="text-white font-black text-xs italic">PS</span>
          </div>
          <span className="text-2xl font-black tracking-tighter">Placement<span className="text-blue-500">Score</span>.online</span>
        </div>
        <div className="hidden lg:flex items-center gap-8 font-bold text-sm text-white/50">
          <button onClick={() => scrollToSection('features')} className="hover:text-white transition">Features</button>
          <button onClick={() => scrollToSection('pricing')} className="hover:text-white transition">Pricing</button>
          <button onClick={() => setView('blog')} className="hover:text-white transition">Blog</button>
          <button onClick={() => scrollToSection('faq')} className="hover:text-white transition">FAQ</button>
          <div className="h-4 w-px bg-white/10" />
          {user ? (
            <div className="flex items-center gap-3 bg-white/5 px-4 py-2 rounded-full border border-white/10">
              <span className="text-xs text-white/80">{user.name}</span>
              <button onClick={() => setView('admin')} className="text-[10px] text-white/20 hover:text-white">Admin</button>
            </div>
          ) : (
            <button onClick={handleGoogleLogin} className="bg-white text-black px-6 py-2.5 rounded-xl font-black hover:bg-blue-500 hover:text-white transition-all flex items-center gap-2">
              <svg className="w-4 h-4" viewBox="0 0 24 24"><path fill="currentColor" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#ea4335" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#fbbc05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z"/><path fill="#4285f4" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>
              Sign In
            </button>
          )}
        </div>
      </div>
    </nav>
  );

  return (
    <main className="min-h-screen bg-[#050505] text-white font-sans selection:bg-blue-500/30 overflow-x-hidden">
      <div className="fixed inset-0 z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-600/5 rounded-full blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-indigo-600/5 rounded-full blur-[120px]" />
      </div>

      <Navbar />

      <AnimatePresence mode="wait">
        {view === 'landing' && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} key="landing" className="relative z-10">
            {/* Hero Section */}
            <section className="pt-48 pb-32 px-6">
              <div className="max-w-7xl mx-auto flex flex-col lg:flex-row items-center gap-20">
                <div className="flex-1 text-center lg:text-left space-y-10">
                  <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 font-bold text-[10px] uppercase tracking-widest">
                    <Sparkles className="w-3 h-3" /> 🔥 24,000+ Students Analysed
                  </motion.div>
                  <h1 className="text-6xl md:text-[80px] font-[1000] leading-[0.9] tracking-tighter">
                    Get Your Real <br /> <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-indigo-500 italic">Placement Score.</span>
                  </h1>
                  <p className="text-xl text-white/40 max-w-2xl lg:mx-0 mx-auto font-medium leading-relaxed">
                    Recruiters spend only 6 seconds on your resume. If your ATS score is below 80, you're getting rejected instantly. Benchmark your career profile now.
                  </p>
                  
                  <div className="flex flex-col sm:flex-row items-center gap-6 justify-center lg:justify-start pt-6">
                    <button onClick={() => scrollToSection('upload')} className="bg-blue-600 text-white px-12 py-6 rounded-[24px] font-black text-xl hover:bg-blue-500 transition-all shadow-2xl shadow-blue-500/30 flex items-center gap-3 group">
                      Scan My Resume <ArrowRight className="group-hover:translate-x-2 transition-transform" />
                    </button>
                    <div className="flex items-center gap-3 p-4 bg-white/5 border border-white/10 rounded-2xl">
                       <ShieldCheck className="text-green-500 w-5 h-5" />
                       <span className="text-[10px] font-black uppercase tracking-widest text-white/30">Privacy Protected</span>
                    </div>
                  </div>
                </div>

                <div className="flex-1 relative">
                  {/* SIGNATURE RING SCORE UI */}
                  <div className="relative w-80 h-80 md:w-[540px] md:h-[540px] mx-auto group">
                    <div className="absolute -inset-4 bg-gradient-to-br from-blue-600/10 to-indigo-600/10 rounded-full blur-3xl opacity-50 group-hover:opacity-100 transition-all duration-1000" />
                    <div className="absolute inset-0 rounded-full border-[1px] border-white/5 animate-spin-slow" />
                    <div className="absolute inset-[10%] rounded-full border-[20px] md:border-[50px] border-white/5 shadow-inner" />
                    <svg className="absolute inset-[10%] w-[80%] h-[80%] -rotate-90 filter drop-shadow-[0_0_15px_rgba(59,130,246,0.3)]">
                      <circle cx="50%" cy="50%" r="45%" stroke="url(#ps-grad)" strokeWidth="45" fill="transparent" strokeDasharray="283%" strokeDashoffset="85%" strokeLinecap="round" className="opacity-90" />
                      <defs>
                        <linearGradient id="ps-grad" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" stopColor="#2563eb" />
                          <stop offset="100%" stopColor="#4f46e5" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                       <motion.span animate={{ scale: [1, 1.05, 1] }} transition={{ repeat: Infinity, duration: 4 }} className="text-9xl md:text-[160px] font-[1000] tracking-tighter leading-none bg-clip-text text-transparent bg-white italic">72</motion.span>
                       <span className="text-xl md:text-2xl font-black text-white/10 uppercase tracking-[0.4em] -mt-4">Placement Score</span>
                       <div className="mt-10 px-8 py-3 bg-blue-600/20 border border-blue-500/50 rounded-full text-xs font-black uppercase tracking-widest text-blue-400 shadow-2xl backdrop-blur-md">Target: 85+</div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Steps Section */}
            <section id="features" className="py-40 px-6 max-w-7xl mx-auto">
               <div className="text-center mb-32 space-y-4">
                  <h2 className="text-6xl font-[1000] italic tracking-tighter uppercase">3 Simple Steps to Success</h2>
                  <p className="text-white/20 font-bold tracking-[0.2em] uppercase text-xs">Transform your job search in minutes</p>
               </div>
               <div className="grid md:grid-cols-3 gap-16 relative">
                  <div className="absolute top-1/2 left-0 w-full h-px bg-gradient-to-r from-transparent via-white/5 to-transparent hidden md:block" />
                  <StepCard num="01" icon={Upload} title="Upload PDF" desc="Drop your resume. Our neural engine extracts text, structure, and semantic metadata instantly." />
                  <StepCard num="02" icon={Terminal} title="3s AI Scan" desc="We benchmark your profile against 500+ proprietary filters used by Workday, Taleo, and Google." />
                  <StepCard num="03" icon={Award} title="Win the Job" desc="Get a data-backed score and a full roadmap to fix keyword gaps and formatting killers." />
               </div>
            </section>

            {/* Deep Insights / Gap Detection */}
            <section className="py-40 px-6 bg-gradient-to-b from-transparent via-blue-600/[0.02] to-transparent">
               <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-32">
                  <div className="flex-1 space-y-16">
                     <h2 className="text-6xl font-black tracking-tighter italic leading-[0.9]">See exactly where you <br /> stand with <span className="text-blue-500">Deep Insights</span></h2>
                     <div className="space-y-8">
                        <InsightItem icon={Search} text="Recruiter readability & OCR compatibility scan" />
                        <InsightItem icon={Target} text="Semantic keyword matching for your target role" />
                        <InsightItem icon={Layout} text="Structural hierarchy & section density analysis" />
                        <InsightItem icon={FileCode} text="AI-powered actionable bullet point re-writing" />
                     </div>
                     <button onClick={() => scrollToSection('pricing')} className="px-12 py-6 bg-white text-black rounded-2xl font-[1000] text-xl shadow-2xl hover:bg-blue-600 hover:text-white transition-all flex items-center gap-3 uppercase italic tracking-tight">Unlock Analysis <ArrowRight /></button>
                  </div>
                  <div className="flex-1">
                     <div className="p-16 bg-[#0A0A0A] rounded-[60px] border border-white/5 shadow-[0_0_100px_rgba(59,130,246,0.1)] relative overflow-hidden group">
                        <div className="absolute inset-0 bg-gradient-to-br from-red-600/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                        <div className="flex items-center gap-6 mb-12 relative z-10">
                           <div className="w-16 h-16 bg-red-500/10 text-red-500 rounded-3xl flex items-center justify-center font-[1000] text-3xl italic ring-1 ring-red-500/20 shadow-lg shadow-red-500/20">!</div>
                           <h4 className="text-3xl font-[1000] italic tracking-tighter uppercase">Critical Gap Found</h4>
                        </div>
                        <p className="text-2xl text-white/40 font-medium leading-relaxed relative z-10 italic">"Missing <span className="text-white">Quantifiable Metrics</span> in 60% of your experience bullet points. ATS systems will rank this profile in the bottom 20% tier."</p>
                        <div className="mt-16 h-3 w-full bg-white/5 rounded-full overflow-hidden relative z-10 shadow-inner">
                           <motion.div initial={{ width: 0 }} whileInView={{ width: '60%' }} transition={{ duration: 1.5, delay: 0.5 }} className="h-full bg-gradient-to-r from-red-600 to-amber-500" />
                        </div>
                     </div>
                  </div>
               </div>
            </section>

            {/* Pricing Section */}
            <section id="pricing" className="py-40 px-6 max-w-7xl mx-auto">
               <div className="text-center mb-32 space-y-4">
                  <h2 className="text-7xl font-[1000] italic tracking-tighter uppercase">No Hidden Fees. Pure Growth.</h2>
                  <p className="text-white/20 font-bold uppercase tracking-[0.3em] text-xs">Chosen by 50,000+ students across India</p>
               </div>
               
               <div className="grid lg:grid-cols-3 gap-10">
                  <PricingCard file={file} setView={setView} setSelectedPlan={setSelectedPlan} tier="BASE" price="99" perks={['Real ATS Score', 'Formatting Audit', 'OCR Compatibility Check', '30-Day Storage']} />
                  <PricingCard file={file} setView={setView} setSelectedPlan={setSelectedPlan} tier="ELITE" price="199" popular perks={['Everything in Base', 'Full Detailed Insight Report', 'Keyword Gap Analysis', 'Recruiter Readability Map', 'Strategic Improvement Plan']} />
                  <PricingCard file={file} setView={setView} setSelectedPlan={setSelectedPlan} tier="EXPERT" price="399" perks={['Everything in Elite', 'AI Bullet Point Rearchitect', 'Unlimited PDF Generations', '1-on-1 Profile Audit', 'Priority Support']} />
               </div>

               {/* COMPREHENSIVE PRICE COMPARISON TABLE */}
               <div className="mt-40 overflow-hidden rounded-[50px] border border-white/5 bg-white/[0.01] shadow-2xl">
                  <table className="w-full text-left border-collapse">
                     <thead className="bg-white/5 text-[11px] font-black uppercase tracking-[0.4em] text-white/10">
                        <tr>
                           <th className="p-10 border-b border-white/5">Core Feature Hub</th>
                           <th className="p-10 border-b border-white/5 text-center">Base</th>
                           <th className="p-10 border-b border-white/5 text-center text-blue-500">Elite</th>
                           <th className="p-10 border-b border-white/5 text-center text-indigo-500">Expert</th>
                        </tr>
                     </thead>
                     <tbody className="font-bold text-sm divide-y divide-white/5">
                        <tr className="hover:bg-white/[0.02] transition-colors">
                           <td className="p-10 text-white/50">ATS Logic Simulation (95%+ Parity)</td>
                           <td className="p-10 text-center text-green-500"><Verified className="w-5 h-5 mx-auto" /></td>
                           <td className="p-10 text-center text-green-500"><Verified className="w-5 h-5 mx-auto" /></td>
                           <td className="p-10 text-center text-green-500"><Verified className="w-5 h-5 mx-auto" /></td>
                        </tr>
                        <tr className="hover:bg-white/[0.02] transition-colors">
                           <td className="p-10 text-white/50">Full Keyword Scan & Density Map</td>
                           <td className="p-10 text-center text-white/10 italic">Limited</td>
                           <td className="p-10 text-center text-blue-500 uppercase tracking-widest text-[10px]">Unrestricted</td>
                           <td className="p-10 text-center text-blue-500 uppercase tracking-widest text-[10px]">Unrestricted</td>
                        </tr>
                        <tr className="hover:bg-white/[0.02] transition-colors">
                           <td className="p-10 text-white/50">Bullet Point Actionable Corrections</td>
                           <td className="p-10 text-center text-white/5 italic">—</td>
                           <td className="p-10 text-center text-green-500"><CheckCircle className="w-5 h-5 mx-auto" /></td>
                           <td className="p-10 text-center text-green-500"><CheckCircle className="w-5 h-5 mx-auto" /></td>
                        </tr>
                        <tr className="hover:bg-white/[0.02] transition-colors">
                           <td className="p-10 text-white/50">AI Content Rewrite & PDF Generation</td>
                           <td className="p-10 text-center text-white/5 italic">—</td>
                           <td className="p-10 text-center text-white/5 italic">—</td>
                           <td className="p-10 text-center text-indigo-500"><Sparkles className="w-5 h-5 mx-auto" /></td>
                        </tr>
                        <tr className="hover:bg-white/[0.02] transition-colors">
                           <td className="p-10 text-white/50">14-Day Placement Success Roadmap</td>
                           <td className="p-10 text-center text-white/5 italic">—</td>
                           <td className="p-10 text-center text-green-500"><CheckCircle className="w-5 h-5 mx-auto" /></td>
                           <td className="p-10 text-center text-green-500"><CheckCircle className="w-5 h-5 mx-auto" /></td>
                        </tr>
                     </tbody>
                  </table>
               </div>
            </section>

            {/* Success Stories Section */}
            <section className="py-40 px-6 bg-indigo-600/[0.02] relative overflow-hidden">
               <div className="max-w-7xl mx-auto relative z-10">
                  <div className="text-center mb-32 space-y-4">
                     <h2 className="text-6xl font-[1000] italic tracking-tighter uppercase">Success Stories</h2>
                     <p className="text-white/20 font-bold uppercase tracking-[0.3em] text-xs">Real students. Real results. Top MNC offers.</p>
                  </div>
                  <div className="grid md:grid-cols-3 gap-10">
                     <TestimonialCard quote="I was getting rejected by every ATS. This tool showed me I was missing basic keywords like 'SDLC'. Fixed it, and got shortlisted the next week!" name="Rahul S." role="Software Engineer @ TCS" />
                     <TestimonialCard quote="The score was eye-opening. I thought my resume was great, but it was failing readability scans. The ₹199 report saved my placement season." name="Priya M." role="Full Stack Dev @ Wipro" />
                     <TestimonialCard quote="Quantifying my achievements as per the suggestions made all the difference. Highly recommend for every engineering student." name="Ankit V." role="Intern @ Infosys" />
                  </div>
               </div>
            </section>

            {/* FAQ Section */}
            <section id="faq" className="py-40 px-6 max-w-4xl mx-auto">
               <div className="text-center mb-24 space-y-4">
                  <h2 className="text-6xl font-[1000] italic tracking-tighter uppercase">Frequently Asked</h2>
                  <p className="text-white/20 font-bold tracking-[0.2em] uppercase text-xs">Your questions, clarified.</p>
               </div>
               <div className="space-y-6">
                  {[
                     { q: "What exactly is an ATS resume score?", a: "An ATS (Applicant Tracking System) score represents how effectively recruitment software used by Fortune 500 firms can parse and rank your resume. High scores (85+) mean you land in the human recruiter's dashboard." },
                     { q: "How accurate is the placement score provided?", a: "Our engine uses algorithms reverse-engineered from major corporate systems like Workday, Greenhouse, and Taleo, maintaining over 95% logic parity with real-world scanners." },
                     { q: "Do you store my resume content permanently?", a: "No. We prioritize privacy. Resumes are processed in volatile server memory and purged immediately after analysis. We only store the final numerical results log for your account dashboard." },
                     { q: "Why is my current score so low (below 50)?", a: "The most common reasons are complex multi-column layouts, tables/graphics that robots can't read, non-standard fonts, or a total lack of role-specific keywords." },
                     { q: "How does the 'Placement Boost' Expert plan work?", a: "In the Expert tier, our AI re-architects your bullet points to emphasize impact using the 'Action + Metric + Result' formula preferred by top-tier consulting and tech firms." }
                  ].map((item, i) => (
                     <div key={i} className="border border-white/5 rounded-[32px] bg-[#0A0A0A] hover:bg-white/[0.02] transition-colors overflow-hidden">
                        <button onClick={() => setActiveFaq(activeFaq === i ? null : i)} className="w-full p-10 flex items-center justify-between text-left group">
                           <span className="text-2xl font-black italic tracking-tight group-hover:text-blue-500 transition-colors uppercase">{item.q}</span>
                           <div className={`w-10 h-10 rounded-full border border-white/10 flex items-center justify-center transition-all ${activeFaq === i ? 'bg-blue-600 border-blue-600 rotate-180' : ''}`}>
                              {activeFaq === i ? <Minus className="w-5 h-5 text-white" /> : <Plus className="w-5 h-5 text-white/20" />}
                           </div>
                        </button>
                        <AnimatePresence>
                           {activeFaq === i && (
                              <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                                 <p className="p-10 pt-0 text-white/40 font-medium text-lg leading-relaxed border-t border-white/5">{item.a}</p>
                              </motion.div>
                           )}
                        </AnimatePresence>
                     </div>
                  ))}
               </div>
            </section>

            {/* Resume Upload Section */}
            <section id="upload" className="py-40 px-6 max-w-5xl mx-auto">
                <div className="text-center mb-24 space-y-4">
                  <h2 className="text-6xl font-black italic tracking-tighter uppercase">Ready to bypass the bot?</h2>
                  <p className="text-white/20 font-black italic uppercase tracking-[0.3em] text-xs">✨ Standard text-based PDF Resume required (Max 5MB)</p>
                </div>
                <div className="relative group">
                  <div className="absolute -inset-2 bg-gradient-to-r from-blue-600 to-indigo-600 rounded-[60px] blur-xl opacity-20 group-hover:opacity-40 transition-opacity" />
                  <div className="relative bg-[#0A0A0A] p-20 rounded-[60px] border border-white/10 shadow-2xl text-center">
                    <input type="file" id="hero-up" className="hidden" accept=".pdf" onChange={handleFileChange} />
                    {!file ? (
                      <label htmlFor="hero-up" className="cursor-pointer block">
                        <div className="p-24 border-2 border-dashed border-white/5 rounded-[40px] hover:border-blue-500/50 transition-all space-y-10 group/label">
                          <Upload className="w-20 h-20 text-white/5 mx-auto group-hover/label:text-blue-500/50 transition-colors" />
                          <div className="space-y-4">
                             <h3 className="text-4xl font-black italic uppercase tracking-tighter">Drag & Drop Resume</h3>
                             <p className="text-white/20 font-black uppercase tracking-[0.3em] text-xs italic">Secure Analysis • Real-time Parsing</p>
                          </div>
                        </div>
                      </label>
                    ) : (
                      <div className="space-y-12 py-10">
                        <FileText className="w-24 h-24 text-blue-500 mx-auto animate-bounce-slow" />
                        <h3 className="text-3xl font-[1000] italic uppercase tracking-tighter">{file.name}</h3>
                        <div className="flex flex-col sm:flex-row gap-6 max-w-md mx-auto">
                           <button onClick={runAnalysis} className="flex-1 py-6 bg-white text-black rounded-3xl font-[1000] text-2xl hover:bg-blue-600 hover:text-white transition-all shadow-2xl">SCAN NOW</button>
                           <label htmlFor="hero-up" className="px-10 py-6 bg-white/5 border border-white/10 rounded-3xl font-black text-xl hover:bg-white/10 transition-all cursor-pointer flex items-center justify-center italic">CHANGE</label>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
            </section>
          </motion.div>
        )}

        {view === 'analyzing' && (
           <motion.div key="analyzing" className="fixed inset-0 z-[200] bg-[#050505] flex flex-col items-center justify-center space-y-12">
              <div className="relative">
                 <div className="w-32 h-32 border-4 border-white/5 rounded-full" />
                 <div className="absolute inset-0 w-32 h-32 border-4 border-blue-500 border-t-transparent rounded-full animate-spin shadow-[0_0_50px_rgba(59,130,246,0.3)]" />
              </div>
              <div className="text-center space-y-2">
                 <h2 className="text-5xl font-[1000] italic tracking-widest uppercase animate-pulse">Neural Parsing...</h2>
                 <p className="text-white/20 font-black uppercase tracking-[0.3em] text-xs">Deconstructing professional metadata</p>
              </div>
           </motion.div>
        )}

        {view === 'result' && (
          <motion.div key="result" className="pt-40 pb-32 px-6 max-w-7xl mx-auto relative z-10">
             <div className="bg-[#0A0A0A] p-20 rounded-[70px] border border-white/5 flex flex-col xl:flex-row gap-24 shadow-[0_0_150px_rgba(0,0,0,0.5)]">
                <div className="text-center space-y-10 xl:w-[400px]">
                   <div className="relative inline-block">
                      <div className="absolute -inset-4 bg-blue-600/20 rounded-full blur-2xl animate-pulse" />
                      <div className="w-64 h-64 rounded-full border-[15px] border-blue-600 flex items-center justify-center relative z-10 bg-black shadow-inner">
                         <span className="text-9xl font-[1000] italic tracking-tighter">{result.score}</span>
                      </div>
                   </div>
                   <div className="space-y-4">
                      <p className="font-black text-xs uppercase tracking-[0.5em] text-white/20">ATS Compatibility Index</p>
                      <button onClick={resetAnalysis} className="flex items-center gap-2 mx-auto px-8 py-3 bg-white/5 hover:bg-white/10 border border-white/5 rounded-full text-blue-500 font-black uppercase tracking-widest text-[10px] transition-all group">
                         <Upload className="w-3 h-3 group-hover:-translate-y-1 transition-transform" />
                         Scan New Resume
                      </button>
                   </div>
                </div>
                
                <div className="flex-1 space-y-16">
                   <div className="space-y-4">
                      <h2 className="text-6xl font-[1000] tracking-tighter italic uppercase flex items-center gap-4">
                         AI Audit Report 
                         <span className={`text-[10px] uppercase font-black tracking-[0.2em] px-4 py-2 rounded-full ring-1 ${isPaid ? 'bg-blue-500/10 text-blue-500 ring-blue-500/20' : 'bg-white/5 text-white/20 ring-white/10'}`}>
                            {isPaid ? selectedPlan?.tier : 'LOCKED'}
                         </span>
                      </h2>
                      <p className="text-white/20 font-bold uppercase tracking-widest text-xs italic">Analysis complete based on corporate hiring benchmarks</p>
                   </div>

                   <div className="space-y-8">
                      <div className={`p-10 bg-green-500/[0.03] rounded-[40px] border border-green-500/10 transition-all ${!isPaid ? 'blur-xl opacity-30 select-none' : ''}`}>
                        <h4 className="text-xl font-black text-green-400 mb-6 uppercase tracking-widest flex items-center gap-3 italic"><CheckCircle className="w-5 h-5" /> Professional Strengths</h4>
                        <div className="grid md:grid-cols-2 gap-4">
                           {result.strengths.map((s:any) => <div key={s} className="p-4 bg-green-500/5 rounded-2xl border border-green-500/5 text-sm font-bold text-white/60 flex items-center gap-3">✓ {s}</div>)}
                        </div>
                      </div>

                      {(isPaid && (selectedPlan?.tier === 'ELITE' || selectedPlan?.tier === 'EXPERT')) ? (
                         <div className="p-10 bg-amber-500/[0.03] rounded-[40px] border border-amber-500/10">
                           <h4 className="text-xl font-black text-amber-400 mb-6 uppercase tracking-widest flex items-center gap-3 italic"><Target className="w-5 h-5" /> Critical Skill Gaps</h4>
                           <div className="flex flex-wrap gap-4">
                              {result.keyword_gaps.map((k:any) => <span key={k} className="px-6 py-3 bg-amber-500/10 rounded-full border border-amber-500/10 text-sm font-black text-amber-500/80 uppercase italic tracking-widest">{k}</span>)}
                              {result.keyword_gaps.length === 0 && <span className="text-green-500 font-black italic">Perfectly Aligned Profile.</span>}
                           </div>
                         </div>
                      ) : isPaid ? null : (
                         <div className="p-10 bg-white/[0.02] rounded-[40px] border border-white/5 blur-sm opacity-20 select-none group relative">
                            <h4 className="text-xl font-black mb-6 italic uppercase">Elite Gap Analysis...</h4>
                            <p className="text-sm font-bold">Upgrade to Elite to view identified missing technical keywords.</p>
                         </div>
                      )}

                      {(isPaid && selectedPlan?.tier === 'EXPERT') && (
                        <div className="p-10 bg-indigo-600/[0.03] rounded-[40px] border border-indigo-600/10">
                           <h4 className="text-xl font-black text-indigo-400 mb-6 uppercase tracking-widest flex items-center gap-3 italic"><Sparkles className="w-5 h-5" /> AI Expert Optimizations</h4>
                           <div className="grid md:grid-cols-2 gap-6 text-[10px] font-black uppercase tracking-[0.2em] text-white/30">
                              <div className="p-6 bg-white/[0.02] rounded-3xl border border-white/5 flex items-center gap-4 hover:border-indigo-500 transition-colors cursor-default">
                                 <Layout className="w-6 h-6 text-indigo-500" /> Standardized Parsing Hierarchy
                              </div>
                              <div className="p-6 bg-white/[0.02] rounded-3xl border border-white/5 flex items-center gap-4 hover:border-indigo-500 transition-colors cursor-default">
                                 <Briefcase className="w-6 h-6 text-indigo-500" /> Metric-First Achievement Re-writing
                              </div>
                              <div className="p-6 bg-white/[0.02] rounded-3xl border border-white/5 flex items-center gap-4 hover:border-indigo-500 transition-colors cursor-default">
                                 <Search className="w-6 h-6 text-indigo-500" /> Latent Semantic keyword injection
                              </div>
                              <div className="p-6 bg-white/[0.02] rounded-3xl border border-white/5 flex items-center gap-4 hover:border-indigo-500 transition-colors cursor-default">
                                 <Globe className="w-6 h-6 text-indigo-500" /> Multi-Scanner Parity Verification
                              </div>
                           </div>
                        </div>
                      )}
                   </div>

                   {!isPaid ? (
                      <div className="space-y-16 pt-12 border-t border-white/5">
                         <div className="text-center space-y-4">
                            <Lock className="w-16 h-16 mx-auto mb-6 text-white/10" />
                            <h3 className="text-4xl font-[1000] italic uppercase tracking-tighter">Upgrade to Unlock Insights</h3>
                            <p className="text-white/20 font-bold text-lg max-w-lg mx-auto italic">Select your success tier to receive professional recommendations and optimization roadmap.</p>
                         </div>
                         <div className="grid sm:grid-cols-3 gap-8">
                            <button onClick={() => { setSelectedPlan({ tier: 'BASE', price: 99 }); setView('payment'); }} className="p-10 rounded-[40px] bg-[#0A0A0A] border border-white/10 hover:border-blue-500 transition-all text-left group shadow-2xl">
                               <h4 className="text-[10px] font-black uppercase tracking-widest text-white/20 mb-2">Base</h4>
                               <div className="text-4xl font-black mb-8 italic">₹99</div>
                               <ul className="text-[10px] space-y-3 text-white/20 font-bold group-hover:text-white/60 transition-colors uppercase tracking-widest">
                                  <li className="flex items-center gap-2"><Check className="w-3 h-3 text-blue-500" /> Core ATS Score</li>
                                  <li className="flex items-center gap-2"><Check className="w-3 h-3 text-blue-500" /> Format Check</li>
                               </ul>
                            </button>
                            <button onClick={() => { setSelectedPlan({ tier: 'ELITE', price: 199 }); setView('payment'); }} className="p-10 rounded-[40px] bg-blue-600/10 border border-blue-500 hover:scale-[1.03] transition-all text-left relative overflow-hidden shadow-2xl group">
                               <div className="absolute top-4 right-4 bg-blue-500 text-[8px] font-[1000] px-3 py-1 rounded-full text-white uppercase italic tracking-widest shadow-xl">Best Choice</div>
                               <h4 className="text-[10px] font-black uppercase tracking-widest text-blue-400 mb-2">Elite</h4>
                               <div className="text-4xl font-black mb-8 text-white italic">₹199</div>
                               <ul className="text-[10px] space-y-3 text-white/60 font-bold uppercase tracking-widest">
                                  <li className="flex items-center gap-2"><Check className="w-3 h-3 text-blue-400" /> Skill Gaps</li>
                                  <li className="flex items-center gap-2"><Check className="w-3 h-3 text-blue-400" /> Roadmap</li>
                                  <li className="flex items-center gap-2"><Check className="w-3 h-3 text-blue-400" /> Readability</li>
                               </ul>
                            </button>
                            <button onClick={() => { setSelectedPlan({ tier: 'EXPERT', price: 399 }); setView('payment'); }} className="p-10 rounded-[40px] bg-[#0A0A0A] border border-white/10 hover:border-indigo-500 transition-all text-left group shadow-2xl">
                               <h4 className="text-[10px] font-black uppercase tracking-widest text-white/20 mb-2">Expert</h4>
                               <div className="text-4xl font-black mb-8 italic">₹399</div>
                               <ul className="text-[10px] space-y-3 text-white/20 font-bold group-hover:text-white/60 transition-colors uppercase tracking-widest">
                                  <li className="flex items-center gap-2"><Sparkles className="w-3 h-3 text-indigo-400" /> AI Resume Builder</li>
                                  <li className="flex items-center gap-2"><Check className="w-3 h-3 text-indigo-400" /> High Priority</li>
                               </ul>
                            </button>
                         </div>
                      </div>
                   ) : (
                      selectedPlan?.tier === 'EXPERT' && (
                         <div className="p-12 rounded-[50px] bg-gradient-to-br from-indigo-600/20 via-blue-600/10 to-transparent border border-white/10 relative overflow-hidden shadow-2xl">
                            <div className="absolute -top-20 -right-20 p-10 opacity-5 pointer-events-none">
                               <Sparkles className="w-80 h-80 text-white" />
                            </div>
                            <div className="relative z-10 space-y-12">
                               <div className="space-y-4">
                                  <h3 className="text-4xl font-[1000] flex items-center gap-4 italic uppercase tracking-tighter">Neural Re-architect <Sparkles className="text-indigo-400 animate-pulse w-8 h-8" /></h3>
                                  <p className="text-xl text-white/40 font-medium max-w-xl italic">Our AI has deconstructed your profile and is ready to rebuild it using high-conversion recruitment patterns.</p>
                               </div>

                               {!isGenerating && !isGenerated && (
                                  <button onClick={handleGenerateAI} className="px-12 py-7 bg-white text-black rounded-[24px] font-[1000] text-2xl hover:bg-blue-600 hover:text-white transition-all shadow-2xl shadow-white/5 uppercase italic tracking-tighter">Generate Optimized Profile</button>
                               )}
                               
                               {isGenerating && (
                                  <div className="flex items-center gap-8 p-10 bg-black/40 rounded-3xl border border-white/5">
                                     <div className="w-16 h-16 border-4 border-white border-t-transparent rounded-full animate-spin shadow-[0_0_30px_rgba(255,255,255,0.2)]" />
                                     <div className="space-y-2">
                                        <p className="font-black text-2xl uppercase italic tracking-widest animate-pulse">Re-architecting...</p>
                                        <p className="text-xs text-white/20 font-black uppercase tracking-[0.4em]">Matching 500+ recruitment signals</p>
                                     </div>
                                  </div>
                               )}

                               {isGenerated && (
                                  <motion.button initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} onClick={handleDownload} className="px-12 py-7 bg-green-500 text-white rounded-[24px] font-[1000] text-2xl hover:bg-green-600 transition-all flex items-center gap-4 shadow-2xl shadow-green-500/30 uppercase italic tracking-tighter">
                                     <CheckCircle className="w-8 h-8" /> Download Optimized PDF
                                  </motion.button>
                               )}
                            </div>
                         </div>
                      )
                   )}
                </div>
             </div>
          </motion.div>
        )}

        {view === 'payment' && (
          <motion.div key="pay" className="pt-48 pb-32 px-6 max-w-2xl mx-auto relative z-10 text-center">
             <div className="bg-[#0A0A0A] p-16 rounded-[60px] border border-white/10 space-y-12 shadow-2xl ring-1 ring-white/5">
                <h2 className="text-5xl font-[1000] tracking-tight uppercase italic flex items-center justify-center gap-4">
                   <Shield className="text-blue-500" /> Checkout
                </h2>
                {paymentStep === 1 && (
                   <div className="space-y-12">
                      <div className="p-14 bg-white/[0.02] rounded-[48px] border border-white/10 relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-600 to-indigo-600" />
                        <span className="text-[10px] font-[1000] uppercase tracking-[0.5em] text-white/20 mb-4 block italic">Invoice for {selectedPlan?.tier || 'ELITE'} Success Tier</span>
                        <span className="text-9xl font-[1000] tracking-tighter italic">₹{selectedPlan?.price || 199}</span>
                        <p className="text-[10px] font-black text-white/10 uppercase tracking-widest mt-4">One-time processing fee</p>
                      </div>
                      <button onClick={() => setPaymentStep(2)} className="w-full py-7 bg-blue-600 rounded-[30px] font-[1000] text-2xl shadow-2xl shadow-blue-500/30 hover:bg-blue-500 transition-all uppercase italic">Pay with UPI / QR Scan</button>
                   </div>
                )}
                {paymentStep === 2 && (
                   <div className="space-y-12">
                      <div className="relative inline-block">
                         <div className="absolute -inset-4 bg-white rounded-[40px] blur-2xl opacity-10" />
                         <div className="bg-white p-8 rounded-[40px] inline-block shadow-2xl relative z-10">
                            <img src="/payment-qr.jpg" alt="QR" className="w-64 h-64" />
                         </div>
                      </div>
                      <div className="text-left space-y-8">
                        <div className="space-y-3">
                           <label className="text-[10px] font-black uppercase text-white/20 ml-2 tracking-[0.3em]">12-Digit UTR Number</label>
                           <input type="text" placeholder="e.g. 812834131941" className="w-full p-7 bg-white/5 border border-white/10 rounded-3xl font-black text-2xl tracking-[0.2em] outline-none focus:border-blue-600 focus:bg-blue-600/5 transition-all text-white placeholder:text-white/5" value={utr} onChange={(e)=>setUtr(e.target.value)} />
                        </div>
                        <div className="space-y-3">
                           <label className="text-[10px] font-black uppercase text-white/20 ml-2 tracking-[0.3em]">PhonePe Transaction ID</label>
                           <input type="text" placeholder="e.g. T260213..." className="w-full p-7 bg-white/5 border border-white/10 rounded-3xl font-black text-2xl tracking-[0.1em] outline-none focus:border-blue-600 focus:bg-blue-600/5 transition-all text-white placeholder:text-white/5" value={transactionId} onChange={(e)=>setTransactionId(e.target.value)} />
                        </div>
                        {paymentError && <div className="p-5 bg-red-500/10 border border-red-500/20 text-red-500 text-xs font-[1000] rounded-2xl uppercase tracking-widest animate-shake italic text-center">{paymentError}</div>}
                        <button onClick={handlePaymentSubmit} className="w-full py-7 bg-white text-black rounded-3xl font-[1000] text-2xl hover:bg-blue-600 hover:text-white transition-all shadow-2xl uppercase italic tracking-tighter">Verify Transaction</button>
                      </div>
                   </div>
                )}
                {paymentStep === 3 && <div className="py-24 space-y-6">
                   <div className="w-20 h-20 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto shadow-[0_0_50px_rgba(59,130,246,0.3)]" />
                   <div className="animate-pulse font-[1000] text-3xl italic uppercase tracking-widest">Validating with Bank...</div>
                </div>}
                {paymentStep === 4 && (
                   <div className="py-20 space-y-12">
                      <div className="relative inline-block">
                         <div className="absolute inset-0 bg-green-500 rounded-full blur-3xl opacity-20 animate-pulse" />
                         <CheckCircle className="w-32 h-32 text-green-500 mx-auto relative z-10" />
                      </div>
                      <div className="space-y-4">
                         <h3 className="text-5xl font-[1000] italic uppercase tracking-tighter">Payment Verified</h3>
                         <p className="text-white/20 font-black uppercase tracking-widest text-xs italic">Unlocking your success roadmap now</p>
                      </div>
                      <button onClick={() => setView('result')} className="w-full py-7 bg-white text-black rounded-3xl font-[1000] text-2xl shadow-2xl hover:scale-105 transition-transform uppercase italic">Access Full Report</button>
                   </div>
                )}
             </div>
          </motion.div>
        )}

        {/* Info Pages (SEO Optimized) */}
        {(['blog', 'contact', 'privacy', 'terms'] as AppState[]).includes(view) && (
           <motion.div key={view} className="pt-48 pb-32 px-6 max-w-6xl mx-auto relative z-10">
              <div className="bg-[#0A0A0A] p-20 rounded-[70px] border border-white/5 shadow-2xl ring-1 ring-white/5">
                 <div className="flex items-center gap-8 mb-20">
                    <button onClick={() => setView('landing')} className="w-16 h-16 bg-white/5 border border-white/5 rounded-3xl flex items-center justify-center hover:bg-white/10 hover:border-blue-500 transition-all group"><ArrowRight className="rotate-180 group-hover:-translate-x-1 transition-transform" /></button>
                    <h2 className="text-7xl font-[1000] capitalize italic tracking-tighter uppercase">{view === 'blog' ? 'Blog & Tips' : view === 'contact' ? 'Support' : view === 'privacy' ? 'Data Shield' : 'Agreement'}</h2>
                 </div>
                 
                 <div className="prose prose-invert max-w-none text-white/40 font-medium leading-relaxed text-xl space-y-16">
                    {view === 'blog' && (
                      <div className="space-y-20">
                        <section className="space-y-8">
                           <h3 className="text-4xl font-[1000] text-white italic uppercase tracking-tighter flex items-center gap-4"><BookOpen className="text-blue-500 w-10 h-10" /> Master Your Career Insights</h3>
                           <p>Welcome to the premium resource hub for Indian engineering and management students. In an era where 75% of resumes are discarded by <strong>Applicant Tracking Systems (ATS)</strong> before a human eyes them, staying ahead of the algorithm is your only strategy. Our blog provides 1,000+ words of actionable, data-backed guidance to secure your future.</p>
                           <p>At <strong>PlacementScore.online</strong>, we analyze thousands of successful hires to reverse-engineer the success patterns of Tier 1 MNCs like TCS, Google, Amazon, and Microsoft.</p>
                        </section>

                        <div className="grid md:grid-cols-2 gap-12">
                           <article className="p-12 bg-white/[0.02] rounded-[50px] border border-white/5 hover:border-blue-500/50 transition-all space-y-6 group">
                              <p className="text-blue-500 font-black text-[10px] uppercase tracking-[0.4em]">Strategy • Feb 13, 2026</p>
                              <h4 className="text-3xl font-black text-white italic leading-tight group-hover:text-blue-400 transition-colors">The Death of the Functional Resume in 2026</h4>
                              <p className="text-lg leading-relaxed">Discover why chronological order is non-negotiable for modern scanners and how "Creative" layouts are currently failing 90% of applicants in campus drives.</p>
                              <div className="pt-6"><span className="text-white font-black text-xs uppercase tracking-widest border-b-2 border-blue-600 pb-1 cursor-pointer">Read Full Insight</span></div>
                           </article>
                           <article className="p-12 bg-white/[0.02] rounded-[50px] border border-white/5 hover:border-blue-500/50 transition-all space-y-6 group">
                              <p className="text-blue-500 font-black text-[10px] uppercase tracking-[0.4em]">Trends • Feb 11, 2026</p>
                              <h4 className="text-3xl font-black text-white italic leading-tight group-hover:text-blue-400 transition-colors">Decoding MNC Hiring Algorithms</h4>
                              <p className="text-lg leading-relaxed">Learn how Fortune 500 firms use skill-density metrics and sentiment analysis to rank candidates. Includes the 2026 "Power Keyword" list for SDE roles.</p>
                              <div className="pt-6"><span className="text-white font-black text-xs uppercase tracking-widest border-b-2 border-blue-600 pb-1 cursor-pointer">Read Full Insight</span></div>
                           </article>
                        </div>
                        
                        <section className="p-16 bg-blue-600/[0.03] rounded-[60px] border border-blue-600/10 space-y-8">
                           <h3 className="text-3xl font-[1000] text-white italic uppercase tracking-tighter">The Universal Success Formula: XYZ</h3>
                           <p>Most students list what they "did." Top candidates list what they "achieved." Our AI optimizer enforces the XYZ formula: Accomplished [X] as measured by [Y], by doing [Z]. Resumes using this pattern receive 4x more interview requests than standard descriptive resumes.</p>
                           <p>By upgrading to the <strong>Expert Plan</strong>, our engine automatically re-architects your work history into this high-impact format, guaranteeing a score jump of 30+ points.</p>
                        </section>
                      </div>
                    )}

                    {view === 'contact' && (
                       <div className="grid lg:grid-cols-2 gap-32">
                          <div className="space-y-16">
                             <div className="space-y-6">
                                <h3 className="text-5xl font-[1000] text-white italic uppercase tracking-tighter leading-[0.9]">Let's Secure Your <br /> <span className="text-blue-500">Global Career.</span></h3>
                                <p className="text-xl leading-relaxed italic">Our expert team in Gurugram and Kolkata provides 24/7 technical support and placement guidance for our premium users.</p>
                             </div>
                             <div className="space-y-10">
                                <div className="flex items-center gap-8 group">
                                   <div className="w-16 h-16 bg-white/5 rounded-[24px] border border-white/5 flex items-center justify-center group-hover:border-blue-500 transition-all"><Mail className="text-blue-500 w-8 h-8" /></div>
                                   <div><h5 className="text-white font-[1000] italic uppercase tracking-tight text-xl">Official Support</h5><p className="font-bold text-white/20">support@placementscore.online</p></div>
                                </div>
                                <div className="flex items-center gap-8 group">
                                   <div className="w-16 h-16 bg-white/5 rounded-[24px] border border-white/5 flex items-center justify-center group-hover:border-blue-500 transition-all"><MapPin className="text-blue-500 w-8 h-8" /></div>
                                   <div><h5 className="text-white font-[1000] italic uppercase tracking-tight text-xl">Headquarters</h5><p className="font-bold text-white/20 italic">Sector V, Salt Lake, Kolkata, India</p></div>
                                </div>
                             </div>
                          </div>
                          <div className="bg-white/5 p-16 rounded-[60px] border border-white/10 space-y-10 shadow-2xl relative overflow-hidden">
                             <div className="absolute top-0 right-0 w-32 h-32 bg-blue-600/5 blur-3xl rounded-full" />
                             <div className="space-y-2">
                                <label className="text-[10px] font-black uppercase text-white/20 ml-3 tracking-[0.3em]">Full Name</label>
                                <input type="text" placeholder="John Doe" className="w-full p-6 bg-black/40 border border-white/10 rounded-3xl outline-none focus:border-blue-600 font-bold transition-all" />
                             </div>
                             <div className="space-y-2">
                                <label className="text-[10px] font-black uppercase text-white/20 ml-3 tracking-[0.3em]">Institution</label>
                                <input type="text" placeholder="IIT / NIT / BITS / VIT" className="w-full p-6 bg-black/40 border border-white/10 rounded-3xl outline-none focus:border-blue-600 font-bold transition-all" />
                             </div>
                             <div className="space-y-2">
                                <label className="text-[10px] font-black uppercase text-white/20 ml-3 tracking-[0.3em]">Message</label>
                                <textarea placeholder="How can our career experts help you?" className="w-full p-6 bg-black/40 border border-white/10 rounded-3xl h-44 outline-none focus:border-blue-600 font-bold transition-all" />
                             </div>
                             <button className="w-full py-7 bg-white text-black rounded-[30px] font-[1000] text-2xl hover:bg-blue-600 hover:text-white transition-all uppercase italic tracking-tighter">Send Inquiry</button>
                          </div>
                       </div>
                    )}

                    {view === 'privacy' && (
                       <div className="space-y-16">
                          <section className="space-y-8">
                             <h3 className="text-4xl font-[1000] text-white italic uppercase tracking-tighter flex items-center gap-5"><ShieldCheck className="text-blue-500 w-12 h-12" /> Information Shield Protocol</h3>
                             <p>At <strong>PlacementScore.online</strong>, we handle highly sensitive professional data. Our privacy architecture is built on the principle of <strong>Zero Permanent Storage</strong>. Resumes are processed in encrypted volatile memory (RAM) and purged immediately after the 30-minute analysis window closes.</p>
                             <p>We use industry-standard 256-bit SSL encryption to ensure that your data is never accessible by third parties during transmission. We do not sell user data to recruiters or lead generators.</p>
                          </section>
                          <div className="grid md:grid-cols-2 gap-10">
                             <div className="p-12 bg-white/[0.02] rounded-[50px] border border-white/5 space-y-6">
                                <h4 className="text-2xl font-[1000] italic uppercase tracking-tighter text-white">Encryption</h4>
                                <p className="text-lg leading-relaxed">All file uploads are tokenized and encrypted at rest using AES-256 standards, ensuring maximum institutional-grade security.</p>
                             </div>
                             <div className="p-12 bg-white/[0.02] rounded-[50px] border border-white/5 space-y-6">
                                <h4 className="text-2xl font-[1000] italic uppercase tracking-tighter text-white">Purge Policy</h4>
                                <p className="text-lg leading-relaxed">Your resume content is systematically deleted from our parsing buffer after 1,800 seconds to comply with global data safety norms.</p>
                             </div>
                          </div>
                       </div>
                    )}

                    {view === 'terms' && (
                       <div className="space-y-16 text-center max-w-4xl mx-auto">
                          <section className="space-y-8">
                             <h3 className="text-5xl font-[1000] text-white italic uppercase tracking-tighter flex items-center justify-center gap-5"><FileSignature className="text-blue-500 w-12 h-12" /> Usage Agreement</h3>
                             <p className="text-2xl italic leading-relaxed">By utilizing the <strong>PlacementScore</strong> engine, you agree to our standard terms of digital service delivery. Due to the immediate delivery of proprietary AI analysis, all sales are final upon report generation.</p>
                             <p className="text-lg text-white/20 font-bold uppercase tracking-widest">Effective Date: February 13, 2026</p>
                          </section>
                          <div className="h-px bg-white/5" />
                          <p className="text-sm font-black uppercase tracking-[0.4em] text-white/10 animate-pulse italic">Providing Data-Driven Confidence to 50,000+ Indian Graduates</p>
                       </div>
                    )}
                 </div>
              </div>
           </motion.div>
        )}

        {view === 'admin' && (
           <motion.div key="admin" className="pt-44 pb-32 px-6 max-w-7xl mx-auto relative z-10">
              <div className="flex justify-between items-center mb-12">
                 <h2 className="text-4xl font-black uppercase italic tracking-tighter">Admin Control</h2>
                 <button onClick={() => setView('landing')} className="bg-white/5 px-6 py-2 rounded-xl text-xs font-black uppercase tracking-widest">Exit</button>
              </div>
              <div className="bg-[#0A0A0A] rounded-[40px] border border-white/5 overflow-hidden shadow-2xl">
                 <table className="w-full text-left">
                    <thead className="bg-white/5 text-[10px] font-black uppercase tracking-[0.3em] text-white/20">
                       <tr><th className="p-10">Student</th><th className="p-10">Plan</th><th className="p-10">UTR</th><th className="p-10">Status</th><th className="p-10 text-right">Action</th></tr>
                    </thead>
                    <tbody className="divide-y divide-white/5 font-bold text-sm">
                       <tr className="hover:bg-white/[0.01] transition-colors"><td className="p-10">Aman S. (IIT-D)</td><td className="p-10 text-blue-500 uppercase tracking-widest italic">Elite</td><td className="p-10 font-mono tracking-widest">882103322199</td><td className="p-10 text-amber-500 italic uppercase tracking-widest">Verification</td><td className="p-10 text-right"><button className="text-green-500 hover:underline uppercase text-xs font-black tracking-widest">Approve</button></td></tr>
                       <tr className="hover:bg-white/[0.01] transition-colors"><td className="p-10">Priya K. (VIT)</td><td className="p-10 text-indigo-500 uppercase tracking-widest italic">Expert</td><td className="p-10 font-mono tracking-widest">991102213122</td><td className="p-10 text-green-500 italic uppercase tracking-widest">Secured</td><td className="p-10 text-right">—</td></tr>
                    </tbody>
                 </table>
              </div>
           </motion.div>
        )}
      </AnimatePresence>

      <footer className="bg-[#020202] pt-40 pb-20 border-t border-white/5 px-6 relative z-10">
         <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between gap-32 border-b border-white/5 pb-32 mb-20">
            <div className="max-w-md space-y-12">
               <div className="flex items-center gap-4 cursor-pointer" onClick={() => setView('landing')}>
                  <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center font-[1000] italic shadow-lg shadow-blue-500/20">PS</div>
                  <span className="text-4xl font-[1000] tracking-tighter">PlacementScore.online</span>
               </div>
               <p className="text-xl text-white/30 font-medium leading-relaxed italic">The definitive AI career benchmark for Indian graduates. Engineered to help you bypass corporate automated filters at TCS, Google, Amazon, and beyond.</p>
               <div className="flex gap-12">
                  <div className="flex items-center gap-3 text-[11px] font-black uppercase tracking-[0.3em] text-white/20"><Shield className="w-5 h-5 text-blue-500" /> Certified Secure</div>
                  <div className="flex items-center gap-3 text-[11px] font-black uppercase tracking-[0.3em] text-white/20">🇮🇳 Made in India</div>
               </div>
            </div>
            <div className="grid grid-cols-2 gap-32">
               <div className="space-y-10">
                  <h5 className="text-[11px] font-[1000] uppercase text-white/10 tracking-[0.4em]">Navigation</h5>
                  <ul className="space-y-6 text-base font-black text-white/40 uppercase tracking-widest italic">
                     <li><button onClick={() => setView('blog')} className="hover:text-blue-500 transition-all">Blog & Tips</button></li>
                     <li><button onClick={() => setView('contact')} className="hover:text-blue-500 transition-all">Contact Us</button></li>
                     <li><button onClick={() => setView('privacy')} className="hover:text-blue-500 transition-all">Privacy Policy</button></li>
                     <li><button onClick={() => setView('terms')} className="hover:text-blue-500 transition-all">Terms of Service</button></li>
                  </ul>
               </div>
               <div className="space-y-10">
                  <h5 className="text-[11px] font-[1000] uppercase text-white/10 tracking-[0.4em]">Expert Support</h5>
                  <div className="space-y-6">
                     <p className="text-sm font-bold text-white/30 leading-relaxed italic uppercase tracking-wider">Our technical team is ready to assist your career journey 24/7.</p>
                     <p className="text-blue-500 font-black text-lg hover:underline cursor-pointer tracking-tight">support@placementscore.online</p>
                  </div>
               </div>
            </div>
         </div>
         <div className="flex flex-col md:flex-row items-center justify-between gap-12 max-w-7xl mx-auto">
            <p className="text-white/20 font-black text-[10px] uppercase tracking-[0.5em] drop-shadow-[0_0_12px_rgba(59,130,246,0.3)] animate-pulse">© 2026 PlacementScore.online. All Rights Reserved.</p>
            <div className="flex items-center gap-3 text-[11px] font-black uppercase tracking-[0.3em] text-white/10 italic">Built with <Heart className="w-4 h-4 text-red-600 fill-current animate-bounce" /> for Bharat's Students</div>
         </div>
      </footer>
    </main>
  );
}

const StepCard = ({ num, icon: Icon, title, desc }: any) => (
   <div className="p-16 bg-[#0A0A0A] rounded-[60px] border border-white/5 hover:border-blue-500/30 transition-all group relative overflow-hidden shadow-2xl">
      <div className="absolute top-0 right-0 p-10 opacity-5 group-hover:opacity-10 transition-opacity"><Icon className="w-32 h-32" /></div>
      <div className="text-6xl font-[1000] text-white/5 mb-10 group-hover:text-blue-500/10 transition-colors italic leading-none">{num}</div>
      <h3 className="text-3xl font-black italic mb-6 uppercase tracking-tighter">{title}</h3>
      <p className="text-xl text-white/40 font-medium leading-relaxed italic">{desc}</p>
   </div>
);

const InsightItem = ({ icon: Icon, text }: any) => (
   <li className="flex items-center gap-6 text-white/60 font-black text-2xl group cursor-default italic tracking-tighter uppercase">
      <div className="w-10 h-10 rounded-2xl bg-blue-500/10 text-blue-500 flex items-center justify-center group-hover:bg-blue-600 group-hover:text-white group-hover:scale-110 transition-all duration-500 ring-1 ring-blue-500/20"><Icon className="w-6 h-6" /></div>
      {text}
   </li>
);

const TestimonialCard = ({ quote, name, role }: any) => (
   <div className="p-16 bg-[#0A0A0A] rounded-[60px] border border-white/5 space-y-10 hover:scale-[1.03] transition-all duration-700 shadow-2xl relative group overflow-hidden">
      <div className="absolute inset-0 bg-blue-600/5 opacity-0 group-hover:opacity-100 transition-opacity" />
      <div className="text-7xl font-serif text-blue-500/10 italic relative z-10 leading-none">"</div>
      <p className="text-2xl text-white/50 font-medium leading-relaxed italic relative z-10 tracking-tight">{quote}</p>
      <div className="pt-10 border-t border-white/5 flex items-center gap-6 relative z-10">
         <div className="w-16 h-16 rounded-[24px] bg-gradient-to-br from-blue-600 to-indigo-600 flex items-center justify-center font-[1000] italic text-2xl shadow-xl shadow-blue-500/20">{name[0]}</div>
         <div className="space-y-1">
            <h4 className="text-xl font-black text-white italic uppercase tracking-tighter">{name}</h4>
            <p className="text-[10px] font-black text-white/20 uppercase tracking-[0.3em] italic">{role}</p>
         </div>
      </div>
   </div>
);

const PricingCard = ({ tier, price, perks, popular, setView, setSelectedPlan, file }: any) => (
  <div className={`p-16 rounded-[70px] bg-[#0A0A0A] border ${popular ? 'border-blue-600 ring-[20px] ring-blue-600/5' : 'border-white/5'} transition-all hover:scale-[1.03] duration-700 flex flex-col shadow-2xl relative overflow-hidden group`}>
     {popular && <div className="absolute top-8 left-1/2 -translate-x-1/2 bg-blue-600 text-white py-2 px-8 rounded-full text-[10px] font-[1000] uppercase italic tracking-[0.3em] shadow-2xl shadow-blue-500/40 z-10">Most Practical</div>}
     <h3 className="text-[11px] font-[1000] tracking-[0.5em] uppercase text-white/20 mb-6 italic">{tier === 'ELITE' || tier === 'GROWTH' ? 'Elite' : tier}</h3>
     <div className="flex items-baseline gap-2 mb-16">
        <span className="text-8xl font-[1000] tracking-tighter italic">₹{price}</span>
        <span className="text-white/20 text-xs font-black uppercase tracking-widest">/{tier === 'EXPERT' ? 'month' : 'scan'}</span>
     </div>
     <ul className="text-left space-y-8 mb-20 flex-1">
        {perks.map((p: any) => <li key={p} className="flex gap-5 items-center text-white/50 font-black text-sm uppercase tracking-tight italic group-hover:text-white/70 transition-colors"><CheckCircle className="w-5 h-5 text-blue-500 shrink-0" /> {p}</li>)}
     </ul>
     <button 
        onClick={() => { 
           if (!file) {
              window.scrollTo({ top: 0, behavior: 'smooth' });
           } else {
              setSelectedPlan({ tier: tier === 'GROWTH' || tier === 'ELITE' ? 'ELITE' : tier, price }); 
              setView('payment');
           }
        }} 
        className={`w-full py-7 rounded-[30px] font-[1000] text-2xl transition-all flex items-center justify-center gap-3 uppercase italic tracking-tighter ${popular ? 'bg-blue-600 text-white shadow-2xl shadow-blue-500/40 hover:bg-blue-500' : 'bg-white/5 border border-white/10 hover:bg-white hover:text-black hover:border-white shadow-xl'}`}
     >
        {tier === 'BASE' ? 'Launch Scan' : tier === 'EXPERT' ? 'Become Expert' : 'Get Elite Report'}
     </button>
  </div>
);
